let services = {
    spotify: 'https://open.spotify.com/user/{NAME}',
    wattpad: 'https://www.wattpad.com/user/{NAME}',
    disqus: 'https://disqus.com/by/{NAME}',
    lastfm: 'https://last.fm/user/{NAME}',
    livejournal: 'https://{NAME}.livejournal.com/',
    poshmark: 'https://poshmark.com/closet/{NAME}',
    myspace: 'https://myspace.com/{NAME}',
    dailymotion: 'https://www.dailymotion.com/{NAME}',
    steam: 'https://steamcommunity.com/id/{NAME}',
    twitter: 'https://twitter.com/{NAME}',
    vsco: 'https://vsco.co/{NAME}/gallery',
    pinterest: 'https://www.pinterest.ca/{NAME}',
    instagram: 'https://instagram.com/{NAME}/',
    ebay: 'https://www.ebay.com/usr/{NAME}',
    reddit: 'https://reddit.com/user/{NAME}',
    gravatar: 'http://gravatar.com/{NAME}',
    smule: 'https://smule.com/{NAME}',
    tumblr: 'https://{NAME}.tumblr.com',
    wordpress: 'https://{NAME}.wordpress.com',

}